### ISSUE TITLE
Błąd w tłumaczeniu flarum-tags.yml

### ISSUE THREAD

**Issue by G4liK** [Flarumeu/flarum-polski#1]
delete_tag_confirmation: "Czy jesteś pewien, że chcesz usunąć **ten** kategorie? Dyskusje oznaczone tą kategorią NIE ZOSTANĄ usunięte."

**Comment by glombers** [comment]
[Update flarum-tags.yml](https://github.com/Flarumeu/flarum-polski/pull/2/commits/f1ebcdab5e6adef87b680b53f6d05b51de0a6c42)
